// ==========================================================================
// In-Memory Fallback Store
// Guarantees zero 500-errors even during MongoDB Atlas network lags/disconnections
// ==========================================================================

export const INITIAL_MENU_ITEMS = [
  {
    _id: 'seed-menu-1',
    category: 'starters',
    name: 'Paneer Tikka',
    description: 'Charcoal-grilled cottage cheese marinated in aromatic tandoori masala.',
    price: 249,
    image: '/pictures-restaurant/Paneer-Tikka.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 340, protein: '16g', carbs: '28g', fats: '14g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-2',
    category: 'starters',
    name: 'Veg Spring Rolls',
    description: 'Crispy golden rolls stuffed with spiced garden vegetables.',
    price: 199,
    image: '/pictures-restaurant/vegetable-spring-rolls.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 280, protein: '6g', carbs: '38g', fats: '10g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-3',
    category: 'starters',
    name: 'Crispy Corn',
    description: 'Golden fried sweet corn tossed with freshly ground pepper and lime.',
    price: 189,
    image: '/pictures-restaurant/crispy-corn.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 240, protein: '5g', carbs: '42g', fats: '8g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-4',
    category: 'starters',
    name: 'Gobi Manchurian',
    description: 'Crispy cauliflower florets in tangy Indo-Chinese garlic sauce.',
    price: 199,
    image: '/pictures-restaurant/gobi-manchurian.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 260, protein: '7g', carbs: '34g', fats: '12g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-5',
    category: 'starters',
    name: 'Paneer 65',
    description: 'Spicy South-Indian style crispy fried cottage cheese cubes.',
    price: 229,
    image: '/pictures-restaurant/paneer-65.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 3,
    nutrition: { calories: 320, protein: '14g', carbs: '22g', fats: '18g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-6',
    category: 'starters',
    name: 'Chicken 65',
    description: 'Iconic deep-fried spiced chicken with curry leaves and green chilies.',
    price: 249,
    image: '/pictures-restaurant/chicken-65.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 3,
    nutrition: { calories: 380, protein: '28g', carbs: '14g', fats: '22g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-7',
    category: 'starters',
    name: 'Tandoori Chicken',
    description: 'Whole chicken leg pieces marinated in spiced yogurt and roasted in clay oven.',
    price: 329,
    image: '/pictures-restaurant/tandoori-chicken.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 350, protein: '36g', carbs: '6g', fats: '18g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-8',
    category: 'biryanis',
    name: 'Chicken Dum Biryani',
    description: 'Authentic Hyderabadi dum biryani with fragrant basmati rice and saffron.',
    price: 299,
    image: '/pictures-restaurant/chicken-dum-biryani.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 520, protein: '30g', carbs: '56g', fats: '18g' },
    customizable: true,
  },
  {
    _id: 'seed-menu-9',
    category: 'biryanis',
    name: 'Mutton Dum Biryani',
    description: 'Slow-cooked tender mutton layered with aromatic basmati rice and royal spices.',
    price: 349,
    image: '/pictures-restaurant/MuttonBiryani.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 580, protein: '32g', carbs: '58g', fats: '24g' },
    customizable: true,
  },
  {
    _id: 'seed-menu-10',
    category: 'biryanis',
    name: 'Royal Veg Biryani',
    description: 'Garden-fresh vegetables and paneer slow-steamed with aged basmati rice.',
    price: 239,
    image: '/pictures-restaurant/veg-biryani.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 360, protein: '10g', carbs: '62g', fats: '8g' },
    customizable: true,
  },
  {
    _id: 'seed-menu-11',
    category: 'fried-rice-noodles',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed long-grain rice with crunchy vegetables and oriental seasoning.',
    price: 199,
    image: '/pictures-restaurant/veg-fried-rice.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 360, protein: '8g', carbs: '64g', fats: '10g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-12',
    category: 'fried-rice-noodles',
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with shredded chicken, egg ribbons, and scallions.',
    price: 239,
    image: '/pictures-restaurant/chicken-fried-rice.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 440, protein: '24g', carbs: '58g', fats: '14g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-13',
    category: 'main-course',
    name: 'Paneer Butter Masala',
    description: 'Fresh cottage cheese cubes in rich, creamy tomato and butter cashew gravy.',
    price: 269,
    image: '/pictures-restaurant/paneer-butter-masala.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 2,
    nutrition: { calories: 410, protein: '18g', carbs: '16g', fats: '30g' },
    customizable: true,
  },
  {
    _id: 'seed-menu-14',
    category: 'main-course',
    name: 'Royal Butter Chicken',
    description: 'Charcoal-grilled tandoori chicken simmered in velvety satin tomato cream gravy.',
    price: 319,
    image: '/pictures-restaurant/butter-chicken.webp',
    tag: 'Non-Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 460, protein: '28g', carbs: '14g', fats: '32g' },
    customizable: true,
  },
  {
    _id: 'seed-menu-15',
    category: 'indian-breads',
    name: 'Butter Naan',
    description: 'Tandoor-baked leavened flatbread brushed generously with pure butter.',
    price: 59,
    image: '/pictures-restaurant/Butter-Naan-3.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 220, protein: '6g', carbs: '38g', fats: '6g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-16',
    category: 'indian-breads',
    name: 'Garlic Herb Naan',
    description: 'Crispy clay oven naan topped with minced garlic and fresh coriander butter.',
    price: 69,
    image: '/pictures-restaurant/Homemade-Garlic-Naan-72-dpi.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 240, protein: '7g', carbs: '40g', fats: '7g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-17',
    category: 'beverages',
    name: 'Punjabi Sweet Lassi',
    description: 'Traditional thick churned yogurt drink with cardamom and saffron.',
    price: 99,
    image: '/pictures-restaurant/Punjabi-Sweet-Lassi-Drink-Recipe.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 210, protein: '7g', carbs: '34g', fats: '5g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-18',
    category: 'beverages',
    name: 'Royal Masala Chai',
    description: 'Freshly brewed aromatic milk tea infused with cardamom, cloves, and ginger.',
    price: 49,
    image: '/pictures-restaurant/Chai_Masala_Tea.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 120, protein: '3g', carbs: '18g', fats: '4g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-19',
    category: 'desserts',
    name: 'Shahi Gulab Jamun',
    description: 'Warm reduced-milk dumplings soaked in rose and cardamom sugar syrup.',
    price: 119,
    image: '/pictures-restaurant/gulab-jamun.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 290, protein: '5g', carbs: '48g', fats: '9g' },
    customizable: false,
  },
  {
    _id: 'seed-menu-20',
    category: 'desserts',
    name: 'Chocolate Lava Cake',
    description: 'Warm dark chocolate cake with a rich molten center, served with vanilla scoop.',
    price: 159,
    image: '/pictures-restaurant/chocolate-lava-cake.webp',
    tag: 'Veg',
    available: true,
    spiceLevel: 1,
    nutrition: { calories: 340, protein: '5g', carbs: '44g', fats: '16g' },
    customizable: false,
  },
];

export const fallbackStore = {
  menuItems: [...INITIAL_MENU_ITEMS],
  orders: [],
  reservations: [],
  events: [],
  contacts: [],
  reviews: [],
};
